version: '3.8'

services:
  cafesphere-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cafesphere_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=CafeSphereDb
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: cafesphere_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: cafesphere_redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
